import type { IconType } from "react-icons";
import {
  SiDotnet,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiAngular,
  SiJquery,
  SiBootstrap,
  SiHtml5,
  SiCss,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiGooglegemini,
  SiClaude,
  SiCursor,
  SiRabbitmq,
  SiGit,
  SiGithub,
  SiGitlab,
  SiJira,
  SiJest,
  SiExpo,
  SiSupabase,
} from "react-icons/si";
import { FaCode, FaDatabase, FaServer, FaPlug, FaBrain, FaRobot, FaLayerGroup, FaBolt } from "react-icons/fa6";

/**
 * Skill name -> logo icon, keyed exactly to the strings in resume.skills.
 * Concepts without a real product/brand (RAG, embeddings, API design, …)
 * get a generic glyph instead of a fabricated logo.
 */
export const skillIcons: Record<string, IconType> = {
  "C#": FaCode,
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  ".NET Core": SiDotnet,
  "ASP.NET MVC": SiDotnet,
  "ASP.NET Web API": SiDotnet,
  WCF: FaServer,
  "Entity Framework": FaDatabase,
  LINQ: FaCode,
  "RESTful API design": FaPlug,
  React: SiReact,
  "React Native": SiReact,
  Angular: SiAngular,
  jQuery: SiJquery,
  Bootstrap: SiBootstrap,
  HTML5: SiHtml5,
  CSS3: SiCss,
  "SQL Server": FaDatabase,
  "PostgreSQL (Supabase)": SiPostgresql,
  MongoDB: SiMongodb,
  "Redis Cache": SiRedis,
  pgvector: SiPostgresql,
  "Google Gemini API": SiGooglegemini,
  "Groq API": FaBolt,
  "Retrieval-Augmented Generation (RAG)": FaBrain,
  "Agentic tool-calling": FaRobot,
  Embeddings: FaLayerGroup,
  Claude: SiClaude,
  "Claude Code": SiClaude,
  ChatGPT: FaRobot,
  Cursor: SiCursor,
  Stitch: FaCode,
  SignalR: FaBolt,
  RabbitMQ: SiRabbitmq,
  Git: SiGit,
  GitHub: SiGithub,
  GitLab: SiGitlab,
  Jira: SiJira,
  SSMS: FaDatabase,
  Jest: SiJest,
  "EAS Build": SiExpo,
  "Supabase Edge Functions": SiSupabase,
};
